### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [aesophor/Wmderland#11]
Would you like to [wrap any pointer data members](https://github.com/aesophor/Wmderland/blob/4737edcb4bc1d883ab9059016cc2cf092ccb9152/src/wm.cpp#L37 "Update candidate: WindowManager class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by aesophor** [comment]
Thank you! 

I read up on smart pointers and decided to wrap the classes `Config`, `Properties` and `Cookie` with std::unique_ptr, since these objects are uniquely owned by the WindowManager and should be automatically destructed by the wm. This way I don't have to manually delete them, which makes memory management easier.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/aesophor/Wmderland/commit/dd0bcdc8b63ba7b2cc1030548e6c0f236a3ddd78 "Wrap various WindowManager data member and Client tree with unique_ptr").
