### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [aesophor/Wmderland#13]
I expect that exception handling is usually supported by a C++ program. I wonder why your function “[main](https://github.com/aesophor/Wmderland/blob/ffa4eb4a66d5fdb20ca6788e8e5ccdbdf1fa7498/src/main.cpp#L17 "main() function")” does not contain [corresponding try and catch instructions](https://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](https://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/try_catch "Description for exception handling")?

**Comment by aesophor** [comment]
Thank you! I'm fairly new to C++ and here's my opinion on this, if I'm wrong please kindly give me advice!

I followed [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Exceptions) and saw they do not use C++ exceptions, also:

* C++ exception handling can only catch the exceptions that are explicitly thrown
* Xlib is a C API and there's no explicitly thrown exceptions (as far as I know)
* I use C++ because I prefer OOP which makes managing data easier for me
* I've also tried adding try-catch block in main.cpp but the binary becomes slightly larger (although I don't really care), plus it doesn't seem to be able to catch any exception

**Comment by elfring** [comment]
How many details do you find relevant from the three information sources (which I referenced)?

**Comment by aesophor** [comment]
I've been reading Matthew Wilson's article, but I don't dare to say that I understand it completely. I did say that there won't be any thrown exceptions before but now I think I was totally wrong, since I use lots of stuff from STL (for example, std::vector) which can throw std::out_of_index.

I've added a try-catch block in main.cpp which catches `const std::exception& ex`. I think this will at least ensure the destructor of WindowManager is called, instead of simply relying on the OS to clean up the mess for us. I've also read that this ensures named pipes/mutex to be cleaned up should the program crashes.

In Matthew Wilson's article, he mentioned that catch (...) is not desirable, since it could catch access violations, divide-by-zero and quench them, (I think this makes it harder to debug), so I decide to catch std::exception only.

**Comment by elfring** [comment]
Will any aspects get more of your software development attention for a “production-quality main()”?
* Clause ordering:
  ```C++
     // 1. Always catch bad_alloc first  
     catch(std::bad_alloc&)  
  ```
* Reaction selection for [uncaught/unhandled exceptions](https://en.cppreference.com/w/cpp/language/throw#Stack_unwinding "Description for stack unwinding")
  “…, it is implementation-defined whether any stack unwinding occurs at all …”

**Comment by aesophor** [comment]
Hi there!
I've added `catch (const std::bad_alloc&)` in ffc0478 (as the first exception to catch).
Also added `catch (...)` to avoid uncaught exceptions which ensures stack unwinding occurs.

**Comment by elfring** [comment]
Thanks for another small source code adjustment.
