### ISSUE TITLE
About the Resize Features / Tab Features like i3 wm ?

### ISSUE THREAD

**Issue by hilarycheng** [aesophor/wmderland#16]
I am a user of i3 wm. Since the WINE app is very annoying in the i3 wm. It will leave border of floating windows of wine when I switch to another desktop. Once I try your tiling wm. It really solve my problems.  Thanks you very much for your work.

Do you have any plan to implements to resize of tiling windows and Tab Features like i3 ? Since I don't much experience of developing the X11 software. I wanna to do it for Wmderland.

**Comment by aesophor** [comment]
Hi,
Thank you very much for trying it out :smile: I'm so happy to receive this issue from you!

> Since the WINE app is very annoying in the i3 wm. It will leave border of floating windows of wine when I switch to another desktop

Yes, I have experienced that too!

> Do you have any plan to implements to resize of tiling windows and Tab Features like i3
* Resize tiling windows: yes --> but I haven't come up with the algorithm for this
* Tab features: probably --> since I didn't use this, but I will try to

However, I'm currently caught up in many things, so perhaps I will work on this after miderm, or even when it's summer (I don't know). For the time being, I'll start thinking of how to implement these feature. and since I'm not very good at algorithms so it's probably gonna take a while

I would be very happy if you would like to play with this project :laughing: the tiling algorithm is [here](https://github.com/aesophor/Wmderland/blob/master/src/workspace.cc#L120), it recursively resizes all windows within a workspace.

---
Also have you experience any crash? On my machine it crashes randomly (~once per week so not a big deal for me). My suspect is that WPS office causes them. 

On Linux Mint (on virtualbox), it crashes even more often then it does on a real machine. I'm really sorry this happens to you :(

Thank you!

**Comment by hilarycheng** [comment]
Then let me try to implements the resizing tiling then I submit a pull request for you to review.

For crash, I just start using for a few days. But I havn't met this problem yet.

**Comment by aesophor** [comment]
No problem, thank you very much!

If you are using **Vim** with **YouCompleteMe** plugin, maybe you'll want to...
1. cmake first to generate config.h from config.h.in
2. `cd src && ln -s ../build/config.h config.h`

or Vim will say that it can't find config.h

**Comment by takagiy** [comment]
Any update on this? Now I've started implementing the resizing feature and it seems to be going well. I might be able to make a good notice in a few days.

Thank you!

**Comment by takagiy** [comment]
![test](https://user-images.githubusercontent.com/18656090/86526377-6c6f5f00-bece-11ea-87bd-24b10654a4fd.png)
It gets almost working!

**Comment by aesophor** [comment]
@takagiy 

Omg Thank you so much for your amazing work!
I've been thinking of implementing this all the time, but I'm still kinda of busy until now, so I haven't gotten my hands on it.
Thank you again! This is amazing!

**Comment by takagiy** [comment]
I opened #47 for this.

**Comment by aesophor** [comment]
@takagiy 

Thank you! I've merged the PR.

I've also made two additional changes to your PR. If you find those changes not reasonable, please let me know. I'll then revert the changes.

Thank you so much!

**Comment by takagiy** [comment]
@aesophor 

Thank you for reviewing and testing my PR in so detail! I looked your additional commits and appreciate your works.

Thank you, again.
