### ISSUE TITLE
XF86 Keys Support

### ISSUE THREAD

**Issue by nikotidar** [aesophor/Wmderland#17]
Hi, sir! I really love your works, i'm using Wmderland for now.
But, it's not support for Xf86 like

1. XF86MonBrightnessUp
2. XF86MonBrightnessDown

When i try to set my keybinds like this

```sh
bindsym XF86MonBrightnessUp exec xbacklight -inc 5
bindsym XF86MonBrightnessDown exec xbacklight -dec 5
```

Wmderland won't start.

Heres the pictures
![Wmderland](https://i.ibb.co/tLv1HN1/IMG-20190516-212725.jpg "Wmderland")

**Comment by aesophor** [comment]
Hi there

Thanks for reporting! But I've been busy with several semester projects, so I'm not able to solve this immediately. I'll take a good look at the source code of `xbindkeys` after this semester, for the time being maybe you could use xbindkeys as a replacement?

```
$ cat ~/.xbindkeysrc
--- trimmed ---
"light -A 10"
    XF86MonBrightnessUp
"light -U 10"
    XF86MonBrightnessDown
--- trimmed ---
```

**Comment by aesophor** [comment]
Hello there,

Full support for XF86 keys has been added since 2c1c63f.

**If you are updating from an old version, please make sure to change:**
`bindsym $Mod+h focus_left` -> `bindsym $Mod+h navigate_left`
`bindsym $Mod+l focus_right` -> `bindsym $Mod+l navigate_right`
`bindsym $Mod+j focus_down` -> `bindsym $Mod+j navigate_down`
`bindsym $Mod+k focus_up` -> `bindsym $Mod+k navigate_up`

Sorry for breaking the backward compatibility.

---
These are the keybinds that I've tested which works well:
```
bindsym XF86MonBrightnessUp exec light -A 10
bindsym XF86MonBrightnessDown exec light -U 10
bindsym XF86KbdBrightnessUp exec kbdlight up 10
bindsym XF86KbdBrightnessDown exec kbdlight down 10
bindsym XF86LaunchA exec rofi -show window
bindsym XF86LaunchB exec rofi -show drun
bindsym XF86AudioPrev exec mpc prev
bindsym XF86AudioNext exec mpc next
bindsym XF86AudioPlay exec mpc toggle
bindsym XF86AudioMute exec amixer -q -D pulse set Master toggle
bindsym XF86AudioRaiseVolume exec amixer -q -D pulse set Master 5%+ unmute
bindsym XF86AudioLowerVolume exec amixer -q -D pulse set Master 5%- unmute
bindsym XF86PowerOff exec qdbus org.kde.ksmserver /KSMServer org.kde.KSMServerInterface.logout -1 -1 -1

bindsym Control+Shift+3 exec scrotutl -f
bindsym Control+Shift+4 exec scrotutl -s
bindsym Control+Shift+space+4 exec
```

If you are still using Wmderland, please clone the latest version from master branch. Also, it is now very stable since multiple bugs have been fixed. Thanks!
