### ISSUE TITLE
Some apps is not closed or killed 100%

### ISSUE THREAD

**Issue by nikotidar** [aesophor/wmderland#27]
Hi, again.
I hope you're not bored with me.

In this case, some applications is not ```closed``` or ```killed``` 100%. I mean, when i using ```telegram-desktop``` then i kill the app it's looks like the app is not closed (running in background). I don't know how to describe this issue, but see the screenshot below.

![Screenshot_2019-11-28_21-42-29](https://user-images.githubusercontent.com/49534825/69815420-daf98980-1228-11ea-8e5a-b357575902e7.png)

Thanks, Marco.

**Comment by aesophor** [comment]
Hi there!

I know what you mean, since I've experienced a similar bug before. The problem is that some programs will unmap their window(s) but not destroying them immediately, leaving an empty window in the workspace (as seen in the screenshot you provided).

Are you running the latest build of this wm? I'm asking because I've fixed this issue ~2 days ago. If you're already running the latest build but still having this problem, please let me know and I'll test it with `telegram-desktop` on my machine. Thanks!

**Comment by nikotidar** [comment]
Umm.. it seems to be affected on another programs. I mean, if you opened some link from terminal (in this case, i'm using urxvt) you'll get two browsers run like mirror display. Check it out my video below.

[Video](https://i.imgur.com/Fgv1JpG.mp4)

**Comment by aesophor** [comment]
I've successfully reproduced this bug with firefox. I'll see if I could fix it!

**Comment by aesophor** [comment]
The patch 78aac749744628c95d03e1c08efd48a1cd33580d is now in master.

Tested it with firefox and the problem no longer exist.

**Comment by nikotidar** [comment]
Confirmed, it's fixed!
Thanks, mate!

**Comment by aesophor** [comment]
Yay!

If you've found any other bug, please let me know! :smile:

**Comment by nikotidar** [comment]
Sure!

Thanks, pal! I really love you window manager :joy:
